---
- name:  install and enable and start httpd service
  hosts: all
  tasks: 
  - name: Install Package
    yum: 
      name:  httpd
      state: latest
  - name: Enable and Start httpd
    service:
      name:    httpd
      state:   started
      enabled: yes
