---
- name:  sample assert stat
  hosts: localhost
  tasks:  
  - name: stat a directory
    stat: 
      path:   /etc/hosts
    regsiter: sta
  - name: assert that /etc/ is a directoy
    assert: 
      that: sta.stat.isdir
