---
- name:  using blocks
  hosts: redhat
  tasks:
  - name: intended to be a success
    block:
    - name: remove a file
      shell:
        cmd: rm -f /var/www/html/index.html
    - name: print status
      debug: 
        msg: block was operated

    rescue:
    - name: create the index file
      shell:
        cmd: echo "hello world" > /var/www/html/index.html
    - name: printing rescue status
      debug:
        msg: rescue was attempted

    always:
    - name: writing a message
      debug: 
        msg: it works

