---
- name: when demo
  hosts: all
  vars: 
    supported_distros:
      - almalinux
      - redhat
      - centos
    mypackage: "vim"
  tasks:
    - debug:
        msg: "Dist is : {{ ansible_distribution }}"
    - name: install on RedHat family
      dnf:  
        name:  "{{ mypackage }}"
        state: present
      when: ansible_distribution in supported_distros


