---
- name:  My Example File
  hosts: all
  gather_facts: no
  tasks: 
    - name: This is Task 1
      debug:
        msg: This is message one
    - name: This is Task 2
      debug:
        msg: This is message two
- name:  This is the 2nd Play!
  hosts: localhost
  gather_facts: no
  tasks:
    - name: This is Task 2
      debug:
        msg: This is message three!
