---
- name:  fileglob
  hosts: localhost
  vars:
    query: "{{ query('fileglob', '~/.*') }}"
    lkup:  "{{ lookup('fileglob', '~/.*') }}"
  tasks:
    - name:  Lookup, just a string
      debug: 
        msg: "Lookup list: {{ lkup }}"
    - name:  Globbed is a list
      debug: 
        msg: "Globbed list: {{ query }}"
    - name:  Loop Globbed List
      debug: 
        msg: "{{ item }}"
      loop:  "{{ query }}"
