---
- name:  handler demo
  hosts: redhat
  tasks: 
  - name: copy index.html
    copy: 
      src:  files/index1.html
      dest: /var/www/html
    notify:
    - restart_web
  handlers: 
  - name: restart_web
    service:
      name:  httpd
      state: restarted
