---
- name:         Synchronise host file
  gather_facts: no
  hosts:        all
  tasks: 
    - name: Copy master hosts to nodes
      ansible.builtin.file:
        src:  /etc/hosts
        dest: /etc/hosts
