---
- hosts: redhat
  var: 
    package: httpd
- hosts: ubuntu
  var:
    package: apache2
- hosts: all
  var:
    service: http

- name:  install and enable and start httpd service
  hosts: redhat
  tasks: 
  - name: Install Package
    ansible.builtin.dnf: 
      name:      "{{ package }}"
      state:     latest

  - name: Enable and Start httpd
    ansible.builtin.service:
      name:      "{{ package }}"
      state:     started
      enabled:   yes

  - name: Allow http access
    ansible.posix.firewalld:
      service:   "{{ service }}"
      permanent: true   # as we know permanent does not apply to the running state
      immediate: true   # so immediate must be set to update the running firewall akin to firewall-cmd --reload.
      state:     enabled
      zone:      public # apply to the default zone

- name:  install and enable and start apache2 service
  hosts: ubuntu 
  tasks: 
  - name: Install Package
    ansible.builtin.apt: 
      name:      "{{ package }}"
      state:     latest

  - name: Enable and Start httpd(apache2)
    service:
      name:      "{{ package }}"
      state:     started
      enabled:   yes

  - name: Check UFW
    ansible.builtin.apt:
      name:      ufw
      state:     present

  - name: Allow http access
    ansible.builtin.command: ufw allow {{ service }}
    #community.general.ufw:
    #this causes a fatal error with ansible-navigator and playbook complains that the version is not up to date
      #rule:      allow
      #port:      "80"
      #proto:     tcp

  - name: Apply ufw
    ansible.builtin.command: ufw reload

- name: Set index.html
  hosts: webservers
  tasks: 
  - name: Create index.html
    ansible.builtin.copy:
      content:   "hello world"
      dest:      "/var/www/html/index.html"

- name: Set index1.html
  hosts: webservers
  tasks: 
  - name: Copy index1.html
    ansible.builtin.copy:
      src:       "index1.html"
      dest:      "/var/www/html/index1.html"

- name: Validate with a curl
  hosts: localhost
  tasks:
  - name: Curl node1
    ansible.builtin.command:
      cmd: curl --silent node1
