---
- name:  install and enable and start httpd service
  hosts: redhat
  tasks: 
  - name: Install Package
    yum: 
      name:  httpd
      state: latest
  - name: Enable and Start httpd
    service:
      name:    httpd
      state:   started
      enabled: yes
---
- name:  install and enable and start apache2 service
  hosts: ubuntu 
  tasks: 
  - name: Install Package
    apt: 
      name:  apache2
      state: latest
  - name: Enable and Start httpd(apache2)
    service:
      name:    apache2
      state:   started
      enabled: yes
---
