---
- name:  Confusingly the slide is titled Lesson 11 but it is Lesson 12!
  hosts: node1.example.com
  vars:
    firewall:
      - name:    http
        zone:    public
        state:   enabled
      - name:    https
        zone:    external
        state:   disabled
      - name:    ssh
        zone:    public
        #state:   
      - name: smb
        #zone:   trusted
        state:   enabled
  tasks:
    - name: Show the firewall rules
      debug:
        msg: "Firewall rules {{ firewall }}"
    - name: Loop the rules
      firewalld:
        service:   "{{ item['name'] }}"
        # if state is not set then the default is enabled
        state:     "{{ item['state'] | default('enabled') }}"
        # omit zone where not set!
        zone:      "{{ item['zone'] | default('omit') }}"
        immediate: true
        permanent: true
      loop: "{{ firewall }}"
      # only include rules where the zone is defined
      #when: "item['zone'] is defined"

