---
- name:  demonstrate loop
  hosts: localhost
  vars_files:
  - vars/loopusers
  tasks:
  - name: show some loops
    debug: 
      msg:  "{{ item['username'] }} is in {{ item['group'] }}"
    loop: "{{ myusers }}"
