---
- name:  network testing
  hosts: all
  ignore_errors: true
  vars: 
    addresses: 
      1.2.3.4/24
      10.0.0.0/8
    netmask: "{{ ansible_default_ipv4['network'] }}/{{ ansible_default_ipv4['netmask'] }}"
  tasks:
    - name:  Print IP Address
      debug:
        msg: The IP Address is {{ ansible_facts['default_ipv4'] }}

    - name:  Is this a valid IP Address
      debug:
        msg: "{{ ansible_facts['default_ipv4']['address'] | ipaddr }}"

    - name:  Agsin but break
      debug:
        msg: "{{ ansible_facts['default_ipv4'] | ipaddr }}"

    - name:  Available space in specified network
      debug:
        msg: "{{ ansible_facts['default_ipv4']['network'] | ipaddr('size') }}"

    - name:  Netmask
      debug:
        msg: "{{ netmask | ipaddr('netmask') }}"
    - name:  Use net to convert to cidr notation
      debug:
        msg: "{{ netmask | ipaddr('net') }}"

    - name:  Host/prefix will filter out only valid host IP addresses and skip net addresses from a list in 1.1.1.1/24
      debug:
        msg: "{{ addresses | ipaddr('host/prefix') }}"
    - name:  Rewrite to IP6
      debug:
        msg: "{{ addresses | ipv4('ipv6') }}"
    - name:  Rewrite to Int
      debug:
        msg: "{{ ansible_facts['default_ipv4']['address'] | ipaddr('int') }}"

    - name:  Find usable IP in range
      debug:
        msg: "{{ '193.179.99.8/27 | ipaddr('range_usable') }}"

