---
- name:  use galaxy nginx role
  hosts: redhat
  pre_tasks:
    - name: remove httpd
      package:
        name:  httpd2
        state: absent
    - name: update packages
      package: 
        name:  "*"
        state: latest
  post_tasks:
    - name: clean dnf
      command: dnf clean
  roles:
    - role: geerlingguy.nginx
