---
- name:  use galaxy nginx role
  hosts: redhat
  pre_tasks:
    - package:
        name:  apache2
        state: absent
    - package: 
        name:  "*"
        state: latest
  post_tasks:
    - name: clean dnf
      command: dnf clean
  roles:
    - role: geerlingguy.nginx
