---
- name:  create user with encrypted passwd
  hosts: node2.example.com
  vars_prompt: 
    - name: passw
      prompt: enter the password to use
  vars: 
    user: sharon
  tasks:
    - debug: 
        msg: "{{ '{{ passw }}' | password_hash('sha512','myrandomsalt') }}"
      register: mypass
    - debug:
        var: mypass
