---
- name:  create user with random password
  hosts: localhost
  gather_facts: no
  vars: 
    mypassword: "{{ lookup('password', 'credentials/' + item + 'length=6') }}"
  tasks:
    - debug: 
        msg: "random_password {{ mypassword }} for user {{ item }}"
      loop:  "{{ query('lines', 'cat users.txt') }}"
