---
- name:  read user ssh keys
  hosts: localhost
  ignore_errors: yes
  vars:
    users:
      #      - student
      - ansible
  tasks: 
    - name: create users
      user: 
        name: "{{ item }}"
      loop: "{{ users }}"
    - name: add authorized keys
      authorized_key:
        user: "{{ item }}"
        key:  "{{ lookup('file', item + '/id_ed25519.pub') }}"
      loop: "{{ users }}"
