---
- name:  copying with a wildcard. example only use sync in real life
  hosts: localhost
  vars:
    src:  "~/ansible_ccat/playbooks/webfiles/*"
    dest: "/tmp"
  tasks: 
    - name: this works but very slowly
      copy:
        src:  "{{ item }}"
        dest: "{{ dest }}"
      # use previously created files, note no '' around src as this would be interpreted as a literal string of 'src'
      loop: "{{ query('fileglob', src) }}"
    - name: this fails as copy does not support wildcard
      copy:
        src:  "{{ src }}"
        dest: "{{ dest }}"
